### ISSUE TITLE
Viewport Sizing

### ISSUE THREAD

**Issue by MattSelf** [studio-cartogram/studioself#10]
Can you set the max size to the 34 point and see how it works. I think we'll have to tweak the "growth" size based on the 20 point minimum at 34 point max, but once we have the extremes it should be easier.

On the project page the rate of scaling is great. Its in 'real time' as the window gets bigger and smaller, but on the homepage the type seems to animate to 'catch up' once the window is finished resizing. I prefer the 'real time' approach. Can this be applied to the homepage?

As for the 'jankiness' I think you mean on the homepage right? The images on the project pages are all basically the same 7:5 ratio, but I know there is probably some discrepancies in actual pixel dimensions.

If it is for the homepage, and there are a limited number of images I have to input the pixel dimension for, I would say option 3 sounds the best. If this means for all the images thats a different story! If number 3 gives me the control to set images to give the variety I was looking for on the homepage, like the sketch file, then it doesn't seem too hard. The homepage would have 3 basic variations in proportion, portrait, landscape and square but I'd love to have more control if possible, as there are already a few cases where different proportions would look best.

Also I think the margin proportions on the project pages might have been altered when the viewport sizing changed, it looks like its a lot more than 18% now. Can you change it back?

**Comment by MattSelf** [comment]
The scaling and type size seems to be working really well now, but I'd like to wait until we get some of the details of image sizes (especially on the homepage) before I start tweaking the growth rate. 2.5 seems to work really well so I don't even know if it will be necessary.

**Comment by cartogram** [comment]
@MattSelf sounds good!

**Comment by feeohnah** [comment]
trying to condense these homepage grid issues into one https://github.com/studio-cartogram/studioself/issues/21
