### ISSUE TITLE
Homepage: Image sizes

### ISSUE THREAD

**Issue by MattSelf** [studio-cartogram/studioself#11]
You wrote:

Right now I'm trying to figure out a way for the page to look less `janky` (technical term) when each image loads. Right now, there are big jumps because as each image loads it pushes the content below it down. I might have figured out a solution for the project pages, but it requires me knowing the aspect ratio (= height / width) of each image. This is something I thought would be built into siteleaf, but is not and requires a plugin.... and installing a plugin requires a Team plan on siteleaf... *frustration*.

A few off the cuff solutions, 1) make each project image have the same dimensions. Looks like most of yours are somewhere around 2560px by ~2000px, this would be a ratio of 78.125% (2000/2560 * 100), 2) Choose from a few pre-defined sizes. For example, portrait and landscape, I would map these to various predefined ratios. 3) Manually enter the image dimensions everytime you upload an image. I would add a width and height field below the image upload box. 4) Let me come up with another way to reduce the jank and load in images gracefully without needing to know the ratio. 

—— 

So I'm pretty sure option 3 sounds the best. If number 3 gives me the control to set images to give the variety I was looking for on the homepage, like the sketch file, then it doesn't seem too hard. The homepage would have 3 basic variations in proportion, portrait, landscape and square but I'd love to have more control if possible, as there are already a few cases where different proportions would look best.

**Comment by MattSelf** [comment]
I'm going to go through the size and upload some new images that are the max size I'm looking for (600x800, 800x600 and 700x700) and see how the effects everything. I've done a couple this morning and they look good! I'm just worried about the image scaling that happens at smaller sizes for mobile as i mentioned in issue #8.

**Comment by feeohnah** [comment]
@MattSelf these scaling issues on mobile can be resolved pretty easily. We were just holding off on addressing them on mobile until we had a viable solution for the back button and homepage thumb sizes.

**Comment by feeohnah** [comment]
@cartogram Images just aren't scaling on mob and as a result are causing massive x-scroll

<img width="380" alt="screen shot 2017-06-28 at 2 46 19 pm" src="https://user-images.githubusercontent.com/2460068/27654695-d7d4feae-5c10-11e7-97d2-aad5991d4127.png">

**Comment by MattSelf** [comment]
Thats great about the mobile being an easy fix. 

I think to clarify, what I’d really like to make sure of is that images are scaling to appropriate window sizes. Making all the images smaller on the homepage looked great at 1440x900, but looked wrong on a desktop (2560x1440 retina).

What I’ve begun to do it put in the images for the largest size, hoping that some scaling can happen that would prevent smaller screens from looking like a single column of images. If this is the case I think the scaling should start to happen before getting to the 1680x1050 (retain) size, which i've noticed is barely containing the images.

Now I don’t know if this is possible through viewport sizing, or what you would recommend. I’d love your input on this. Maybe I will have to upload 2 sizes of thumbnail, and specify both of their dimensions in the CMS? One at the largest size and one at the smaller size, similar to what you guys uploaded? 

I've attached images of the smaller images you posted (which fit the size) and the newest size of thumbnail which sometimes forces everything into a single column.

![preview1](https://user-images.githubusercontent.com/28766277/27695585-58b395d8-5cbd-11e7-8224-f89244e812d8.jpg)
![preview2](https://user-images.githubusercontent.com/28766277/27695584-58b338cc-5cbd-11e7-9a10-2bb4070388bf.jpg)

**Comment by feeohnah** [comment]
@cartogram Looking better, Captions are too close to the images now though

<img width="385" alt="screen shot 2017-06-29 at 5 20 07 pm" src="https://user-images.githubusercontent.com/2460068/27710937-5f50b01a-5cef-11e7-8257-e7ddf63b5694.png">
