### ISSUE TITLE
Homepage: Image scaling

### ISSUE THREAD

**Issue by MattSelf** [studio-cartogram/studioself#12]
There are still a few issues with the steps of scaling, and I've tested the site on a few devices where it looks off because the images haven't stepped up to the next size yet. Could you have a look at this and let me know what you think?

I'm wondering if we just need to alter the dimensions where the images step up, add a step, or maybe theres a more complex reason.

The viewport scaling of the type is great, maybe we just need to sync it with the images stepping now? Theres a few cases where the images have jumped to a smaller size and look tiny next to the type, which also bumps onto 2 lines when the image is so small.

**Comment by MattSelf** [comment]
One other element of the homepage related to the scaling is that the position of the images seem to be related to the outer edges of the page, and the space in between the images grows depending on the window size. They should be more relating to each other like the tumblr example (http://www.amandahaas.ch/), and centred in the middle of the window.

Also the space between rows of images is a bit tight now, and should open up a bit. This is pretty minor compared to the other issues so maybe this is more like a final finishing detail once the other issues are resolved.

**Comment by feeohnah** [comment]
@MattSelf we may have resolved this by just uploading thumbnails with the exact dimensions you like it to be on the homepage in this issue: https://github.com/studio-cartogram/studioself/issues/6 let us know.

**Comment by feeohnah** [comment]
@MattSelf trying to condense these homepage spacing issues into one, because I think they are all related to this https://github.com/studio-cartogram/studioself/issues/21
