### ISSUE TITLE
Project Order on Homepage

### ISSUE THREAD

**Issue by MattSelf** [studio-cartogram/studioself#14]
Is there any way to have the order of the list on the siteleaf projects page reflect the order which the projects are displayed on the homepage? Right now I have to change the published date, which is pretty slow.

**Comment by cartogram** [comment]
@MattSelf oh yes absolutely! There is one option that I can configure where new, yet to be sorted projects can show up at the top of the list or at the bottom. I set it to the top, but I can put them to end if you'd prefer that, just let me know.

**Comment by MattSelf** [comment]
No this is perfect, thanks!
