### ISSUE TITLE
Navigation: "Close"

### ISSUE THREAD

**Issue by MattSelf** [studio-cartogram/studioself#16]
Can the "Close" button on the project page act more like a "back" button so that the homepage doesn't load back at the top? Right now it requires the user to scroll back to the spot they left off, rather than it going directly back to where they were. Thanks!

**Comment by MattSelf** [comment]
In addition, the "Next Project" button on every page is still linking to the chronological order, rather than the order which they appear on the homepage.

**Comment by cartogram** [comment]
@MattSelf created a seperate issue for the Next project button here https://github.com/studio-cartogram/studioself/issues/17

**Comment by cartogram** [comment]
@MattSelf should be done!
