### ISSUE TITLE
Underlines

### ISSUE THREAD

**Issue by MattSelf** [studio-cartogram/studioself#19]
I really like the resolution to the underlines, it looks and works great. Theres just one thing that needs a fix, which is that they are different thicknesses for the different fonts used, so for the body text its a bit different than the "Studio Self" home button. Can these be consistent?

**Comment by feeohnah** [comment]
@MattSelf Can you provide screenshots of the different thicknesses? I've grabbed some screenshots from Chrome and Firefox and when I overlay them, they appear to be the same, but maybe I'm missing something.

![self-underlines-chrome](https://user-images.githubusercontent.com/2460068/27654335-ef57a0d2-5c0f-11e7-8886-63932f46edc8.jpg)
![self-underlines-firefox](https://user-images.githubusercontent.com/2460068/27654336-ef58f93c-5c0f-11e7-98d4-35f5bc7df353.jpg)

**Comment by MattSelf** [comment]
I think this might just be an issue on an older monitor, let me have a look at a few other places and let you know. if I don't see it I wouldn't worry about this.

**Comment by feeohnah** [comment]
@MattSelf I'll close this for now and we can reopen later if we catch it again, I haven't seen it yet on any of the browsers/devices I have tested
