### ISSUE TITLE
Add more space between last paragraph of info & contact

### ISSUE THREAD

**Issue by feeohnah** [studio-cartogram/studioself#2]
<img width="808" alt="screen shot 2017-05-09 at 2 55 34 pm" src="https://cloud.githubusercontent.com/assets/2460068/25854383/b3cc51da-34c7-11e7-8dbb-22d8af346440.png">
<img width="1279" alt="screen shot 2017-05-09 at 2 55 53 pm" src="https://cloud.githubusercontent.com/assets/2460068/25854382/b3c50e52-34c7-11e7-982e-718eec993111.png">

**Comment by cartogram** [comment]
@capreasy can't this be done in the admin?

**Comment by cartogram** [comment]
@capreasy is this resolved, did you try this?
