### ISSUE TITLE
Details

### ISSUE THREAD

**Issue by MattSelf** [studio-cartogram/studioself#20]
Just a small issue with alignment with the different fonts. Also I think the caption under the images on the homepage has become too close now.
![alignment1](https://user-images.githubusercontent.com/28766277/27698090-142d83ae-5cc4-11e7-8061-5bf9c7b189ad.jpg)
![alignment2](https://user-images.githubusercontent.com/28766277/27698091-15709440-5cc4-11e7-94ff-2104bd8f328b.jpg)

**Comment by feeohnah** [comment]
@MattSelf I've adjusted the bottom margins of the images on the grid. @cartogram maybe we can use something like [this](https://sassline.com/) to make sure that the different baselines of the different webfonts align?

**Comment by feeohnah** [comment]
@MattSelf ready for your review!

**Comment by MattSelf** [comment]
Looks perfect now
