### ISSUE TITLE
Load Screen

### ISSUE THREAD

**Issue by MattSelf** [studio-cartogram/studioself#22]
Hi guys, this is probably just a small addition, but I've noticed a few people struggle with the load screen requiring a tap or click to fade away (and no written prompt for it). People just start scrolling. Is there a way that scrolling can make it fade away the same way a click would? One of the early examples, studiolin.org, does it with both. Is this something you could add? Thanks!

**Comment by feeohnah** [comment]
@MattSelf  not a problem, have a look and let us know if this behaves as you were expecting
