### ISSUE TITLE
Name in Window

### ISSUE THREAD

**Issue by MattSelf** [studio-cartogram/studioself#23]
Another small thing guys, just wondering if instead of the project name being in the top centre of the browser window, could it still just say Studio Self? Thanks!

![screen shot 2017-07-07 at 10 34 42 am](https://user-images.githubusercontent.com/28766277/27962489-14bc7c20-6300-11e7-81e0-9f14f1e74bb3.png)

**Comment by feeohnah** [comment]
@MattSelf that was an easy one! Should be just the site title now.
