### ISSUE TITLE
Space between end of project images and description should be increased on mobile

### ISSUE THREAD

**Issue by feeohnah** [studio-cartogram/studioself#4]
<img width="398" alt="screen shot 2017-05-09 at 3 10 27 pm" src="https://cloud.githubusercontent.com/assets/2460068/25854994/cf644892-34c9-11e7-9a6c-f0bfb39afda5.png">
<img width="446" alt="screen shot 2017-05-09 at 3 10 36 pm" src="https://cloud.githubusercontent.com/assets/2460068/25854997/d020017c-34c9-11e7-97aa-0ca7e742dfab.png">

@cartogram should be equal to the space between end of description and Next link

**Comment by feeohnah** [comment]
@cartogram also seems like his line-height is tighter 20/24 you've got 20/30

**Comment by feeohnah** [comment]
@cartogram still seems like the space before the description starts could be increased, doubled maybe?

<img width="453" alt="screen shot 2017-06-19 at 12 04 06 pm" src="https://user-images.githubusercontent.com/2460068/27294456-a2be0592-54e7-11e7-8012-eb014d90c96a.png">

**Comment by cartogram** [comment]
@capreasy this was marked as review a long time ago, did you look at it?
