### ISSUE TITLE
Fix image sizes

### ISSUE THREAD

**Issue by cartogram** [studio-cartogram/studioself#6]
Break Points
For the homepage, I had initially designed the sketch file to reflect the breakpoints at the sizes when the images would jump up or down to the next size. Right now, they’re scaling. I’d really like the homepage to function more like my starting point for the site — the tumblr theme www.amandahaas.ch — with images re-shuffling, and jumping to the next size when the window reaches the breakpoint. 

Image sizes
Every image has an identical width right now. Is there a way to have the sketch file reflected more closely, with vertical and horizontal images being different widths? In my max size in the sketch file (at the largest size), I had the horizontal and vertical images images at 800x600, and a square image at 700x700. Is there a way to specify this in the project admin page?

**Comment by cartogram** [comment]
@capreasy in this case, should he just upload an image with the sizes he wants?

**Comment by feeohnah** [comment]
@MattSelf We think this can be achieved by uploading a thumbnail image that is the exact dimensions you want (for example 640px x 480 px). I've uploaded some new thumbnail images for each of your projects, let us know if this is what you were after.
