### ISSUE TITLE
Image margins

### ISSUE THREAD

**Issue by cartogram** [studio-cartogram/studioself#8]
Sorry to change my mind on this again, but I think the margins on the project page should be 18%. I did some looking around at some other sites and I think this is the sweet spot! Also, I just noticed that even though we discussed 20% its actually a bit more than that in chrome, like around 22% or something. I just want to make its bang on 18%, since we’ve spent the time deliberating this, haha.

**Comment by MattSelf** [comment]
Hey guys, looks like the project page margins were altered when the viewport sizing was deployed. Could you change it back to 18% of the window width? Also, on mobile devices, the margins have also been increased. Could they be changed back also? Thanks

**Comment by feeohnah** [comment]
@cartogram I still think there needs to be some padding between images, the sketch file is pretty consistent with ~60px between each image and ~74 px between each row.

<img width="943" alt="screen shot 2017-06-25 at 6 40 11 pm" src="https://user-images.githubusercontent.com/2460068/27520321-6fbe71c4-59d6-11e7-9578-a1719f8b45d7.png">

<img width="842" alt="screen shot 2017-06-25 at 6 43 04 pm" src="https://user-images.githubusercontent.com/2460068/27520317-5b47450e-59d6-11e7-811f-c19eb1515f93.png">

**Comment by MattSelf** [comment]
The homepage needs to have consistent padding between images, right now it fluctuates based on the window dimension. The only variable would be the outer margins between images and the window edges. The padding should always be 60 between images and 75 (or 74) between rows.

**Comment by MattSelf** [comment]
Some strange things happening at mobile sizes too, where the images are not scaling down to the correct width. See screenshot attached. Alos, I swear I wrote about this already but I can't find my previous comment, maybe I didn't hit the 'comment' button. So please ignore if this is doubling up.

<img width="512" alt="screen shot 2017-06-27 at 11 44 13 am" src="https://user-images.githubusercontent.com/28766277/27599745-b9b2eb4a-5b37-11e7-93bb-31c24ff63ebf.png">

**Comment by feeohnah** [comment]
@MattSelf can you confirm if we've resolved the mobile issue you were seeing? 

The other is related to this https://github.com/studio-cartogram/studioself/issues/21

**Comment by MattSelf** [comment]
Mobile is working really well, all the padding and spacing is great.
