### ISSUE TITLE
Safari issues

### ISSUE THREAD

**Issue by cartogram** [studio-cartogram/studioself#9]
I had some strange results when I opened the site with safari, where the mobile only version appeared, so every project thumbnail was stacked vertically. I know Safari isn’t a developers favourite browser to work with but this was definitely a noticeable problem.

**Comment by MattSelf** [comment]
Looks like Safari is doing some strange things with the italic type, squishing it and slanting the text. Could this be changed to just the real italic font, the way it looks in chrome?

**Comment by cartogram** [comment]
@MattSelf fixed this, see before and after below:

<img width="173" alt="screenshot 2017-06-25 17 11 08" src="https://user-images.githubusercontent.com/462077/27519777-703c7b08-59c9-11e7-9476-ec79ace44ca6.png">
<img width="205" alt="screenshot 2017-06-25 17 09 27" src="https://user-images.githubusercontent.com/462077/27519776-70350468-59c9-11e7-8b7a-a267f1c2be6f.png">
